Algoritmo "ex05"

Var
  palavra, letra1, letra2, letra3, letra4, letra5, letra6: caracter

Inicio
  escreval("Digite uma palavra: ")
  leia(palavra)
  letra1:= COPIA(palavra, 1,1)
  escreval(letra1)
  letra2:= COPIA(palavra, 2,1)
  escreval(letra2)
  letra3:= COPIA(palavra, 3,1)
  escreval(letra3)
  letra4:= COPIA(palavra, 4,1)
  escreval(letra4)
  letra5:= COPIA(palavra, 5,1)
  escreval(letra5)
  letra6:= COPIA(palavra, 6,6)
  escreval(letra6)

Fimalgoritmo