algoritmo "ex22"

Var
 c: caracter
 i: inteiro
 
Inicio
 c:="A"
 i:=ASC(c)
 Escreval(i)
 c:="E"
 i:=ASC(c)
 Escreval(i)
 c:="I"
 i:=ASC(c)
 Escreval(i)
 c:="O"
 i:=ASC(c)
 Escreval(i)
 c:="U"
 i:=ASC(c)
 Escreval(i)
 
 c:="a"
 i:=ASC(c)
 Escreval(i)
 c:="e"
 i:=ASC(c)
 Escreval(i)
 c:="i"
 i:=ASC(c)
 Escreval(i)
 c:="o"
 i:=ASC(c)
 Escreval(i)
 c:="u"
 i:=ASC(c)
 Escreval(i)
 
fimalgoritmo